---
galaxy_info:
  role_name: common
  author: vladgh
  description: Vlad's Common Role
  license: Apache v2
  min_ansible_version: '2.14'
  galaxy_tags: []
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Debian
      versions:
        - bookworm
        - bullseye
dependencies:
  - role: ansible.posix
  - role: community.general
