---
galaxy_info:
  role_name: common
  author: vladgh
  description: Vlad's Common Role
  license: Apache v2
  min_ansible_version: '2.11'
  galaxy_tags: []
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Debian
      versions:
        - bullseye
        - buster
dependencies: []
