---
# Accounts
local_groups: []
local_users: []

# APT
apt_repositories: []

# APT Packages
additional_packages: []

# Python
pip_install_packages: []
pip_user_install_packages: []

# CA Certificates
## Set to `yes` to install all certificates from `files/ca`
install_ca_certificates: no

# Cronjobs
cron_jobs: []

# Mount points
mounts: []
systemd_mounts: []

# Security
## Set to `yes` to install and configure Fail2ban
fail2ban_enabled: no
## SSH port for the fail2ban configuration
fail2ban_ssh_port: 22
## Set to `yes` to enable unattended upgrades
unattended_upgrades_autoupdate_enabled: no
unattended_upgrades_autoupdate_reboot: "false"
unattended_upgrades_autoupdate_reboot_time: "03:33"
unattended_upgrades_autoupdate_mail_to: ""
unattended_upgrades_autoupdate_mail_on_error: no
unattended_upgrades_autoupdate_blacklist: []

# Miscellaneous
## Set to `yes` to disable lid switch on laptops.
disable_lid_switch: no
