---
# Timezone
timezone: ''

# Accounts
local_groups: []
local_users: []

# APT
apt_extra_keys: []
apt_extra_repositories: []
apt_disable_repositories: []

# APT Packages
additional_packages: []

# Python
pip_install_packages: []
pip_user_install_packages: []

# CA Certificates
## Set to `true` to install all certificates from `files/ca`
install_ca_certificates: false

# BASH extra aliases
bash_extra_aliases: []

# Cronjobs
cron_jobs: []

# SYSCTL
sysctl_overwrite: {}

# Mount points
mounts: []
systemd_mounts: []

# Unattended upgrades
unattended_upgrades_autoupdate_enabled: false
unattended_upgrades_autoupdate_reboot: false
unattended_upgrades_autoupdate_reboot_time: "03:33"
unattended_upgrades_autoupdate_mail_to: ""
unattended_upgrades_autoupdate_mail_on_error: false
unattended_upgrades_autoupdate_blacklist: []

# Shell
shell_extra_commands: []

# Miscellaneous
## Set to `true` to disable lid switch on laptops.
disable_lid_switch: false
