---
galaxy_info:
  role_name: dns
  author: vladgh
  description: Vlad's DNS Role
  license: Apache v2
  min_ansible_version: '2.11'
  galaxy_tags: []
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Debian
      versions:
        - bookworm
        - bullseye
dependencies: []
