name: Unreleased

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  unreleased:
    name: Refresh changelog (generate Unreleased section)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Generate CHANGELOG.md
        run: docker run -e CHANGELOG_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v "$(pwd)":/usr/local/src/your-app githubchangeloggenerator/github-changelog-generator --user ${{ github.repository_owner }} --project ${{ github.event.repository.name }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog
          file_pattern: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
